### ISSUE TITLE
rq: Export Script.json from UI

### ISSUE THREAD

**Issue by subtleGradient** [anutron/mootools-depender#1]
The depender UI would be awesome for creating your script.json files in the first place!
oh yeah!

**Comment by subtleGradient** [comment]
Well, I guess you'd have to add a lot to the UI to allow for selecting the dependencies for multiple scripts at once and adding a description to your script.

**Comment by anutron** [comment]
yeah, depender is a client of the scripts.json list, not the other way around. If you want a tool that does that for you, it's not this one.
