### ISSUE TITLE
URL link on http://mootools.net/blog/2009/11/09/mootools-depender-a-build-tool-for-mootools-javascript-libraries/ links to the wrong Github URL

### ISSUE THREAD

**Issue by rogerhu** [anutron/mootools-depender#5]
Your blog posting on http://mootools.net/blog/2009/11/09/mootools-depender-a-build-tool-for-mootools-javascript-libraries/ links the GitHub repository of http://github.com/mootools/mootools-depender/. 

It looks like the correct URL is http://github.com/anutron/mootools-depender

**Comment by anutron** [comment]
fixed!
